# Generated by Django 5.2.6 on 2025-10-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the employee.', max_length=120)),
                ('email', models.EmailField(help_text='Employee’s unique email address.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number (optional).', max_length=30)),
                ('address', models.TextField(blank=True, help_text='Residential address (optional).')),
                ('date_of_joining', models.DateField(help_text='The date the employee joined the organization.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Performance rating from 1 (Poor) to 5 (Excellent).')),
                ('review_date', models.DateField(help_text='Date when the performance review was recorded.')),
                ('employee', models.ForeignKey(help_text='Employee being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'date_of_joining'], name='employees_e_departm_b85b99_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['employee', 'review_date'], name='employees_p_employe_d7da61_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['rating'], name='employees_p_rating_bd1ff4_idx'),
        ),
    ]
