# Generated by Django 5.2.6 on 2025-09-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_date', models.DateField()),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'date_of_joining'], name='employees_e_departm_b85b99_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['employee', 'review_date'], name='employees_p_employe_d7da61_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['rating'], name='employees_p_rating_bd1ff4_idx'),
        ),
    ]
